name: Auto Crawl Movie Data

on:
  schedule:
    # 1h sáng VN = 18h tối hôm trước (UTC)
    # 12h trưa VN = 5h sáng (UTC)
    # 18h tối VN = 11h trưa (UTC)
    - cron: '0 18,5,11 * * *'
  workflow_dispatch: # Cho phép bấm chạy thủ công

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run crawl script
        run: python crawl_anime.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # Thêm cả file json và file text lưu ngày chạy
          git add data_2026_perfect.json last_run.txt
          # Kiểm tra nếu không có gì thay đổi thì không commit để tránh lỗi Action
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update phim: $(date)" && git push)
