name: Auto Crawl Catalog

# Kịch bản chạy: Bấm tay hoặc chạy tự động 0h sáng hàng ngày (giờ VN)
on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run Crawler
        run: |
          python crawler_anime_rap.py
          python crawler_phim_quoc_gia.py
          python crawler_others.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Auto Update Data: $(date)" || echo "No changes to commit"
          git push
