name: Auto Update Gist Domain

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  update-domain:
    runs-on: ubuntu-latest
    
    # Cấp cả quyền đọc repo và quyền viết Gist cho Token nội bộ
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm init -y
          npm install puppeteer

      - name: Run script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node update-gist.js
